services:
  app:
    image: dferriz/sample-nodejs:app
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_USER_ID=1000
        - APP_GROUP_ID=1000
      target: build-dev
    restart: always
    volumes:
      - app_node_builds:/opt/node_builds
      - ../:/var/www

volumes:
  app_node_builds:
